### ISSUE TITLE
installer l'env sur le poste local et faire passer les tests

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/karibou-wallet#2]
Il faut suivre la documentation de la page README
> il y a peut être un test qui ne passe pas! tu peux m'envoyer le output ici

**Comment by patedavid** [comment]
Alors voila l'output de l'erreur:
` 1) driver.mongoose.wallet Creating new transaction using an empty wallet:

      Uncaught AssertionError: expected 'Le service de paiement n\'est plus disponible (2)' to be 'Le montant sur votre compte est insuffisant !'
      + expected - actual

      -Le service de paiement n'est plus disponible (2)
      +Le montant sur votre compte est insuffisant !
      
      at Assertion.fail (node_modules/should/cjs/should.js:258:17)
      at Assertion.value (node_modules/should/cjs/should.js:335:19)
      at Timeout._onTimeout (test/wallet.0.driver.js:219:30)`
