### ISSUE TITLE
vérifier avec stripe/connect certaines questions 

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/karibou-wallet#4]
### nous utilisons stripe/connect avec le mode de transfert en 2 temps , cf. la doc concernant le [`transfer_group`](https://stripe.com/docs/connect/charges-transfers#grouping-transactions)
1. est-il possible de transférer plus que ce qui a été payé par la carte de crédit 
Exemple;  Un client achete pour 100.- de marchandise dont 50 .- sont payé avec un bon «giftcode», seul 50.- sont payés avec la carte de crédit.  Dans ce cas nous devons quand même transférer 100.- 

2. est-il possible de faire un `partial_refund` après un transfert, sinon comment  gérer ça?

**Comment by patedavid** [comment]
[https://stripe.com/docs/connect/charges-transfers#issuing-refunds](https://stripe.com/docs/connect/charges-transfers#issuing-refunds)
> However, refunding a charge has no impact on any associated transfers

Donc, il est nécessaire d'annuler (partiellement) un transfert, indépendamment de la charge, en indiquant le montant à retirer.
[https://stripe.com/docs/connect/charges-transfers#reversing-transfers](https://stripe.com/docs/connect/charges-transfers#reversing-transfers)

**Comment by patedavid** [comment]
Concernant la limite de temps pour les refund, il ne semble pas y en avoir:
[https://stripe.com/docs/refunds](https://stripe.com/docs/refunds)
> Your customer sees the refund as a credit 
> ...
> Some refunds—those issued shortly after the original charge—appear in the form of a reversal instead of a refund.

**Comment by evaletolab** [comment]
il faut encore savoir s'il est possible de faire un transfert de 100 .- avec une charge de 50 .- !! en effet peut bénéficier d'un bon de 50.-  :fire: :fire:
